name: deploy workflow

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      ## 원격 환경에 코드 복사ja
      - name: copy project
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete # rsync 명령어 옵션
          remote_path: /home/ubuntu/app/profanity-filter-api
          remote_host: ${{ secrets.DEV_SERVER_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEV_SSH_KEY }}

      ## deploy setup
      - name: deploy setup and gradle build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/profanity-filter-api
            touch  /home/ubuntu/app/profanity-filter-api/src/main/resources/application-prod.yml
            echo "${{ secrets.APPLICATION_PROD }}" | base64 --decode > src/main/resources/application-prod.yml  
            chmod +x gradlew
            ./gradlew build -x test

      ## 개발 도커 실행
      - name: docker compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/ubuntu/app/profanity-filter-api
            # 기존 실행 중인 컨테이너 중지 및 제거
            docker stop dev-profanity-filter-api || true
            docker rm dev-profanity-filter-api || true
            # Docker Compose를 이용한 컨테이너 빌드 및 실행
            docker-compose -f docker-compose-dev.yml up -d --no-deps --build dev-profanity-filter-api
            # 사용하지 않는 이미지 정리
            docker image prune -f
